### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Also a small question: do you @HenryLoenwind have the plan to support the torch(es) from carpenter's block and terrafirmacraft?

### CODE REVIEW

**Comment by HenryLoenwind** [comment]
Thx.

Yes, I do. Thx for bringing them to my attention.

**Comment by HenryLoenwind** [comment]
just a quick question about tfc: Looking at the lang file, I see two torches;

```
tile.Torch.name=Torch
tile.TorchOff.name=Extinguished Torch
```

I guess I should place only the first one?

**Comment by 3TUSK** [comment]
The torch in tfc can be automatically extinguished after about 2 in-game days. 
And you are right, we only need the first one, that is: 

```
tile.Torch.name=Torch
```

**Comment by HenryLoenwind** [comment]
Funny detail: If I had detected vanilla torches the same way as modded torches, tfc would have worked from the beginning.

New version is online, I'd love some feedback if it works.

**Pull request merged**
