### PR TITLE
Fixed entity click NPE

### PR DESCRIPTION
**Pull request by thecodewarrior**
No longer crashes when pressing the place torch key while looking at an
entity

### CODE REVIEW

**Comment by thecodewarrior** [comment]
Also your travis needs to to have grade updated... :P

**Comment by HenryLoenwind** [comment]
Interesting, what was the crash?

I know, I'd have to checkin the gradle with the project. I kind of hoped travis would update some time, so I don't have to do that...

**Comment by thecodewarrior** [comment]
A NPE when the player clicks on an an entity, because apparently objectMouseOver.hitVec is null in that case.

**Comment by HenryLoenwind** [comment]
BTW: I haven't forgotten you, I just was busy. I've looked at the code and I think I'm missing something else, too. I'll have a better look at this when I'm back from my mini-vacation next Monday.

**Comment by thecodewarrior** [comment]
Thanks for telling me. Too few people (myself included) do that.

**Comment by HenryLoenwind** [comment]
Ok, I had a look at what I did and I wasn't impressed. To my defense, when I originally coded the mod it was for my own use, not for publication.

So I re-implemented the right-click handling in a cleaner way instead of using you band-aid.

Thanks for bringing this issue to my attention!

**Pull request closed without merging**
